//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Blog.DataAccess.Data.Blogging
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserRole
    {
        public int UserId { get; set; }
        public int RoleId { get; set; }
        public int CreatedByUserId { get; set; }
        public System.DateTime CreateDateTime { get; set; }
        public Nullable<int> UpdatedByUserId { get; set; }
        public Nullable<System.DateTime> UpdatedDateTime { get; set; }
    }
}
