//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Blog.DataAccess.Data.Blogging
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserPerson
    {
        public int UserId { get; set; }
        public int PersonId { get; set; }
        public string Association { get; set; }
    }
}
